/*
 * Lightweight EEPROM recovery for production firmware.
 * It restores one selected factory profile when the EEPROM marker is invalid.
 */

struct IntConfigEntry
{
  uint16_t address;
  uint16_t value;
};

#if EEPROM_RECOVERY_PROFILE_ID == PROFILE_ID_3000W
const IntConfigEntry recoveryProfile[] PROGMEM = {
    {ADR_ASSISTMODE, 3},
    {ADR_BATCAP_AH, 192},
    {ADR_BATCAP_WH, 1114},
    {ADR_LVC, 390},
    {ADR_FULL_BATT_V, 540},
    {ADR_MVPERA, 40},
    {ADR_CURDIR, 0},
    {ADR_VOL_DIV, 33058},
    {ADR_CUR_SENSOR_OK, 0},
    {ADR_CUR_PROT, 2},
    {ADR_TOT_MIN, 79},
    {ADR_TOT_MAX, 360},
    {ADR_TIN_MIN, 90},
    {ADR_TIN_MAX, 380},
    {ADR_THR_RESET, 1},
    {ADR_THR_SAFE_VOLTAGE, 390},
    {ADR_KPHMPH, 0},
    {ADR_PERIMETER, 2163},
    {ADR_MOT_MAG, 1},
    {ADR_GEAR_RATIO, 10},
    {ADR_BT_BUTTONS, 0},
    {ADR_EBRAKEHILO, 0},
    {ADR_TEMPCTEMPF, 0},
    {ADR_TEMPTYPE1, 3},
    {ADR_TEMPTYPE2, 1},
    {ADR_OVHT1, 140},
    {ADR_OVHT2, 60},
    {ADR_POWERKP, 150},
    {ADR_POWERKI, 80},
    {ADR_POWERKD, 50},
    {ADR_P_LOW, 0},
    {ADR_I_LOW, 0},
    {ADR_D_LOW, 0},
    {ADR_LOW_THRESHOLD, 0},
    {ADR_SPEEDFACTORMIN, 1},
    {ADR_PIDPWMMAX, 200},
    {ADR_SPEEDFACTOR_RAMP_UP, 40},
    {ADR_CRUISE_CONTROL_POWER_MIN, 240},
    {ADR_CRUISE_CONTROL_POWER_MAX, 1300},
    {ADR_CRUISE_CONTROL_POWER_RAMP_UP, 300},
    {ADR_CRUISE_CONTROL_MAX_SPEED, 40},
    {ADR_AUTOLEGAL, 1},
    {ADR_LEGALLIMIT_ON_OFF, 1},
    {ADR_LEGALLIMIT_SPEED, 25},
    {ADR_LEGALLIMIT_POWER, 250},
    {ADR_PASMAGNETS, 12},
    {ADR_PWR_LIM_PAS_1, 100},
    {ADR_PWR_LIM_PAS_2, 180},
    {ADR_PWR_LIM_PAS_3, 250},
    {ADR_PWR_LIM_PAS_4, 350},
    {ADR_PWR_LIM_PAS_5, 600},
    {ADR_SPD_LIM_PAS_1, 20},
    {ADR_SPD_LIM_PAS_2, 25},
    {ADR_SPD_LIM_PAS_3, 25},
    {ADR_SPD_LIM_PAS_4, 30},
    {ADR_SPD_LIM_PAS_5, 38},
    {ADR_MIN_SPD_PAS_1, 0},
    {ADR_MIN_SPD_PAS_2, 0},
    {ADR_MIN_SPD_PAS_3, 0},
    {ADR_MIN_SPD_PAS_4, 0},
    {ADR_MIN_SPD_PAS_5, 0},
    {ADR_CAD_MIN_PAS_1, 0},
    {ADR_CAD_MIN_PAS_2, 0},
    {ADR_CAD_MIN_PAS_3, 0},
    {ADR_CAD_MIN_PAS_4, 0},
    {ADR_CAD_MIN_PAS_5, 0},
    {ADR_CAD_MAX_PAS_1, 10},
    {ADR_CAD_MAX_PAS_2, 10},
    {ADR_CAD_MAX_PAS_3, 10},
    {ADR_CAD_MAX_PAS_4, 10},
    {ADR_CAD_MAX_PAS_5, 10},
    {ADR_RAMP_UP_PAS_1, 300},
    {ADR_RAMP_UP_PAS_2, 300},
    {ADR_RAMP_UP_PAS_3, 300},
    {ADR_RAMP_UP_PAS_4, 400},
    {ADR_RAMP_UP_PAS_5, 500},
    {ADR_BOOST_POWER_PAS_1, 500},
    {ADR_BOOST_POWER_PAS_2, 500},
    {ADR_BOOST_POWER_PAS_3, 750},
    {ADR_BOOST_POWER_PAS_4, 800},
    {ADR_BOOST_POWER_PAS_5, 1000},
    {ADR_BOOST_TIME_PAS_1, 3500},
    {ADR_BOOST_TIME_PAS_2, 3500},
    {ADR_BOOST_TIME_PAS_3, 3500},
    {ADR_BOOST_TIME_PAS_4, 3500},
    {ADR_BOOST_TIME_PAS_5, 3500},
    {ADR_BOOST_SPEED_PAS_1, 10},
    {ADR_BOOST_SPEED_PAS_2, 10},
    {ADR_BOOST_SPEED_PAS_3, 10},
    {ADR_BOOST_SPEED_PAS_4, 22},
    {ADR_BOOST_SPEED_PAS_5, 30},
    {ADR_BOOST_RAMP_UP_PAS, 5000},
    {ADR_CADENCE_COUNT_TIME, 250},
    {ADR_ENABLE_TORQUE_SENSOR, 0},
    {ADR_STARTUP_WEIGHT_ON_PEDAL, 180},
    {ADR_TORQUE_SENSOR_ADC_MIN, 315},
    {ADR_TORQUE_SENSOR_ADC_MAX, 620},
    {ADR_TORQUE_SENSOR_KGF_MAX, 600},
    {ADR_PWR_LIM_THR_1, 100},
    {ADR_PWR_LIM_THR_2, 250},
    {ADR_PWR_LIM_THR_3, 500},
    {ADR_PWR_LIM_THR_4, 1000},
    {ADR_PWR_LIM_THR_5, 1000},
    {ADR_MODE_THR_1, 0},
    {ADR_MODE_THR_2, 0},
    {ADR_MODE_THR_3, 0},
    {ADR_MODE_THR_4, 1},
    {ADR_MODE_THR_5, 1},
    {ADR_RAMP_UP_THR_1, 3000},
    {ADR_RAMP_UP_THR_2, 3000},
    {ADR_RAMP_UP_THR_3, 3000},
    {ADR_RAMP_UP_THR_4, 3000},
    {ADR_RAMP_UP_THR_5, 3000},
};
#endif

#if EEPROM_RECOVERY_PROFILE_ID == PROFILE_ID_6000W
const IntConfigEntry recoveryProfile[] PROGMEM = {
    {ADR_ASSISTMODE, 5}, {ADR_BATCAP_AH, 400}, {ADR_BATCAP_WH, 2890}, {ADR_LVC, 600}, {ADR_FULL_BATT_V, 830}, {ADR_MVPERA, 10}, {ADR_CURDIR, 0}, {ADR_VOL_DIV, 33187}, {ADR_CUR_SENSOR_OK, 0}, {ADR_CUR_PROT, 30},
    {ADR_TOT_MIN, 85}, {ADR_TOT_MAX, 350}, {ADR_TIN_MIN, 90}, {ADR_TIN_MAX, 370}, {ADR_THR_RESET, 1}, {ADR_THR_SAFE_VOLTAGE, 370}, {ADR_KPHMPH, 0}, {ADR_PERIMETER, 1890}, {ADR_MOT_MAG, 46}, {ADR_GEAR_RATIO, 10},
    {ADR_BT_BUTTONS, 0}, {ADR_EBRAKEHILO, 1}, {ADR_TEMPCTEMPF, 0}, {ADR_TEMPTYPE1, 3}, {ADR_TEMPTYPE2, 1}, {ADR_OVHT1, 120}, {ADR_OVHT2, 60}, {ADR_POWERKP, 200}, {ADR_POWERKI, 70}, {ADR_POWERKD, 140},
    {ADR_P_LOW, 50}, {ADR_I_LOW, 30}, {ADR_D_LOW, 50}, {ADR_LOW_THRESHOLD, 300}, {ADR_SPEEDFACTORMIN, 1}, {ADR_PIDPWMMAX, 200}, {ADR_SPEEDFACTOR_RAMP_UP, 50}, {ADR_CRUISE_CONTROL_POWER_MIN, 240}, {ADR_CRUISE_CONTROL_POWER_MAX, 1300}, {ADR_CRUISE_CONTROL_POWER_RAMP_UP, 300},
    {ADR_CRUISE_CONTROL_MAX_SPEED, 40}, {ADR_AUTOLEGAL, 1}, {ADR_LEGALLIMIT_ON_OFF, 0}, {ADR_LEGALLIMIT_SPEED, 28}, {ADR_LEGALLIMIT_POWER, 350}, {ADR_PASMAGNETS, 36}, {ADR_PWR_LIM_PAS_1, 5}, {ADR_PWR_LIM_PAS_2, 10}, {ADR_PWR_LIM_PAS_3, 15}, {ADR_PWR_LIM_PAS_4, 20},
    {ADR_PWR_LIM_PAS_5, 1100}, {ADR_SPD_LIM_PAS_1, 55}, {ADR_SPD_LIM_PAS_2, 55}, {ADR_SPD_LIM_PAS_3, 55}, {ADR_SPD_LIM_PAS_4, 55}, {ADR_SPD_LIM_PAS_5, 37}, {ADR_MIN_SPD_PAS_1, 0}, {ADR_MIN_SPD_PAS_2, 0}, {ADR_MIN_SPD_PAS_3, 0}, {ADR_MIN_SPD_PAS_4, 0},
    {ADR_MIN_SPD_PAS_5, 3}, {ADR_CAD_MIN_PAS_1, 0}, {ADR_CAD_MIN_PAS_2, 0}, {ADR_CAD_MIN_PAS_3, 0}, {ADR_CAD_MIN_PAS_4, 0}, {ADR_CAD_MIN_PAS_5, 0}, {ADR_CAD_MAX_PAS_1, 10}, {ADR_CAD_MAX_PAS_2, 10}, {ADR_CAD_MAX_PAS_3, 10}, {ADR_CAD_MAX_PAS_4, 10},
    {ADR_CAD_MAX_PAS_5, 10}, {ADR_RAMP_UP_PAS_1, 350}, {ADR_RAMP_UP_PAS_2, 350}, {ADR_RAMP_UP_PAS_3, 350}, {ADR_RAMP_UP_PAS_4, 350}, {ADR_RAMP_UP_PAS_5, 350}, {ADR_BOOST_POWER_PAS_1, 500}, {ADR_BOOST_POWER_PAS_2, 500}, {ADR_BOOST_POWER_PAS_3, 800}, {ADR_BOOST_POWER_PAS_4, 1100},
    {ADR_BOOST_POWER_PAS_5, 1000}, {ADR_BOOST_TIME_PAS_1, 1500}, {ADR_BOOST_TIME_PAS_2, 2000}, {ADR_BOOST_TIME_PAS_3, 2000}, {ADR_BOOST_TIME_PAS_4, 2000}, {ADR_BOOST_TIME_PAS_5, 1500}, {ADR_BOOST_SPEED_PAS_1, 20}, {ADR_BOOST_SPEED_PAS_2, 25}, {ADR_BOOST_SPEED_PAS_3, 55}, {ADR_BOOST_SPEED_PAS_4, 55},
    {ADR_BOOST_SPEED_PAS_5, 29}, {ADR_BOOST_RAMP_UP_PAS, 5000}, {ADR_CADENCE_COUNT_TIME, 250}, {ADR_ENABLE_TORQUE_SENSOR, 1}, {ADR_STARTUP_WEIGHT_ON_PEDAL, 100}, {ADR_TORQUE_SENSOR_ADC_MIN, 325}, {ADR_TORQUE_SENSOR_ADC_MAX, 620}, {ADR_TORQUE_SENSOR_KGF_MAX, 750}, {ADR_PWR_LIM_THR_1, 60}, {ADR_PWR_LIM_THR_2, 100},
    {ADR_PWR_LIM_THR_3, 100}, {ADR_PWR_LIM_THR_4, 100}, {ADR_PWR_LIM_THR_5, 100}, {ADR_MODE_THR_1, 0}, {ADR_MODE_THR_2, 0}, {ADR_MODE_THR_3, 0}, {ADR_MODE_THR_4, 0}, {ADR_MODE_THR_5, 0}, {ADR_RAMP_UP_THR_1, 3500}, {ADR_RAMP_UP_THR_2, 5000},
    {ADR_RAMP_UP_THR_3, 5000}, {ADR_RAMP_UP_THR_4, 5000}, {ADR_RAMP_UP_THR_5, 5000},
};
#endif

#if EEPROM_RECOVERY_PROFILE_ID == PROFILE_ID_10000W
const IntConfigEntry recoveryProfile[] PROGMEM = {
    {ADR_ASSISTMODE, 3}, {ADR_BATCAP_AH, 440}, {ADR_BATCAP_WH, 3190}, {ADR_LVC, 600}, {ADR_FULL_BATT_V, 835}, {ADR_MVPERA, 10}, {ADR_CURDIR, 1}, {ADR_VOL_DIV, 33058}, {ADR_CUR_SENSOR_OK, 0}, {ADR_CUR_PROT, 20},
    {ADR_TOT_MIN, 85}, {ADR_TOT_MAX, 350}, {ADR_TIN_MIN, 90}, {ADR_TIN_MAX, 360}, {ADR_THR_RESET, 1}, {ADR_THR_SAFE_VOLTAGE, 370}, {ADR_KPHMPH, 0}, {ADR_PERIMETER, 2050}, {ADR_MOT_MAG, 32}, {ADR_GEAR_RATIO, 10},
    {ADR_BT_BUTTONS, 0}, {ADR_EBRAKEHILO, 1}, {ADR_TEMPCTEMPF, 0}, {ADR_TEMPTYPE1, 4}, {ADR_TEMPTYPE2, 0}, {ADR_OVHT1, 140}, {ADR_OVHT2, 60}, {ADR_POWERKP, 190}, {ADR_POWERKI, 100}, {ADR_POWERKD, 80},
    {ADR_P_LOW, 0}, {ADR_I_LOW, 0}, {ADR_D_LOW, 0}, {ADR_LOW_THRESHOLD, 0}, {ADR_SPEEDFACTORMIN, 1}, {ADR_PIDPWMMAX, 70}, {ADR_SPEEDFACTOR_RAMP_UP, 30}, {ADR_CRUISE_CONTROL_POWER_MIN, 240}, {ADR_CRUISE_CONTROL_POWER_MAX, 2000}, {ADR_CRUISE_CONTROL_POWER_RAMP_UP, 260},
    {ADR_CRUISE_CONTROL_MAX_SPEED, 40}, {ADR_AUTOLEGAL, 1}, {ADR_LEGALLIMIT_ON_OFF, 0}, {ADR_LEGALLIMIT_SPEED, 25}, {ADR_LEGALLIMIT_POWER, 250}, {ADR_PASMAGNETS, 12}, {ADR_PWR_LIM_PAS_1, 500}, {ADR_PWR_LIM_PAS_2, 700}, {ADR_PWR_LIM_PAS_3, 900}, {ADR_PWR_LIM_PAS_4, 1100},
    {ADR_PWR_LIM_PAS_5, 1100}, {ADR_SPD_LIM_PAS_1, 20}, {ADR_SPD_LIM_PAS_2, 25}, {ADR_SPD_LIM_PAS_3, 30}, {ADR_SPD_LIM_PAS_4, 35}, {ADR_SPD_LIM_PAS_5, 35}, {ADR_MIN_SPD_PAS_1, 0}, {ADR_MIN_SPD_PAS_2, 0}, {ADR_MIN_SPD_PAS_3, 0}, {ADR_MIN_SPD_PAS_4, 0},
    {ADR_MIN_SPD_PAS_5, 0}, {ADR_CAD_MIN_PAS_1, 0}, {ADR_CAD_MIN_PAS_2, 0}, {ADR_CAD_MIN_PAS_3, 0}, {ADR_CAD_MIN_PAS_4, 0}, {ADR_CAD_MIN_PAS_5, 0}, {ADR_CAD_MAX_PAS_1, 10}, {ADR_CAD_MAX_PAS_2, 10}, {ADR_CAD_MAX_PAS_3, 10}, {ADR_CAD_MAX_PAS_4, 10},
    {ADR_CAD_MAX_PAS_5, 10}, {ADR_RAMP_UP_PAS_1, 200}, {ADR_RAMP_UP_PAS_2, 200}, {ADR_RAMP_UP_PAS_3, 400}, {ADR_RAMP_UP_PAS_4, 500}, {ADR_RAMP_UP_PAS_5, 500}, {ADR_BOOST_POWER_PAS_1, 2000}, {ADR_BOOST_POWER_PAS_2, 2000}, {ADR_BOOST_POWER_PAS_3, 2000}, {ADR_BOOST_POWER_PAS_4, 2000},
    {ADR_BOOST_POWER_PAS_5, 2000}, {ADR_BOOST_TIME_PAS_1, 3500}, {ADR_BOOST_TIME_PAS_2, 3500}, {ADR_BOOST_TIME_PAS_3, 3500}, {ADR_BOOST_TIME_PAS_4, 3500}, {ADR_BOOST_TIME_PAS_5, 3500}, {ADR_BOOST_SPEED_PAS_1, 10}, {ADR_BOOST_SPEED_PAS_2, 10}, {ADR_BOOST_SPEED_PAS_3, 22}, {ADR_BOOST_SPEED_PAS_4, 27},
    {ADR_BOOST_SPEED_PAS_5, 27}, {ADR_BOOST_RAMP_UP_PAS, 5000}, {ADR_CADENCE_COUNT_TIME, 250}, {ADR_ENABLE_TORQUE_SENSOR, 0}, {ADR_STARTUP_WEIGHT_ON_PEDAL, 180}, {ADR_TORQUE_SENSOR_ADC_MIN, 315}, {ADR_TORQUE_SENSOR_ADC_MAX, 620}, {ADR_TORQUE_SENSOR_KGF_MAX, 600}, {ADR_PWR_LIM_THR_1, 1000}, {ADR_PWR_LIM_THR_2, 35},
    {ADR_PWR_LIM_THR_3, 35}, {ADR_PWR_LIM_THR_4, 50}, {ADR_PWR_LIM_THR_5, 100}, {ADR_MODE_THR_1, 1}, {ADR_MODE_THR_2, 0}, {ADR_MODE_THR_3, 0}, {ADR_MODE_THR_4, 0}, {ADR_MODE_THR_5, 0}, {ADR_RAMP_UP_THR_1, 1000}, {ADR_RAMP_UP_THR_2, 500},
    {ADR_RAMP_UP_THR_3, 500}, {ADR_RAMP_UP_THR_4, 2000}, {ADR_RAMP_UP_THR_5, 2000},
};
#endif

template <size_t N>
void writeIntConfigTable(const IntConfigEntry (&entries)[N])
{
  for (size_t i = 0; i < N; i++)
  {
    uint16_t address = pgm_read_word(&entries[i].address);
    uint16_t value = pgm_read_word(&entries[i].value);
    EEPROM.updateInt(address, value);
  }
}

void recoverEEPROM()
{
  EEPROM.updateInt(ADRFIRSTTIME, FIRST_TIME_CODE);
  EEPROM.updateInt(ADR_PROFILE_ID, EEPROM_RECOVERY_PROFILE_ID);

  EEPROM.updateFloat(ADRDIST, 0.0);
  EEPROM.updateFloat(ADRWHUSED, 0.0);
  EEPROM.updateFloat(ADRVMAX, 0.0);
  EEPROM.updateFloat(ADRMVTIME, 0.0);
  EEPROM.updateFloat(ADRTRIP, 0.0);
  EEPROM.updateFloat(ADRWHUSEDKM, 0.0);
  EEPROM.updateFloat(ADRPMAX, 0.0);
  EEPROM.updateFloat(ADRIMAX, 0.0);
  EEPROM.updateFloat(ADRMAHUSED, 0.0);
  EEPROM.updateFloat(ADRWHUSEDKMDTG, 0.0);
  EEPROM.updateFloat(ADRTRIPDTG, 0.0);
  EEPROM.updateFloat(ADRTOTMAHUSED, 0.0);
  EEPROM.updateFloat(ADRLASTVOLTAGE, 95.0);
  EEPROM.updateFloat(ADRWHUSEDMTG, 0.0);
  EEPROM.updateFloat(ADRMVTIMEMTG, 0.0);
  EEPROM.updateFloat(ADRTOTMH, 0.0);
  EEPROM.updateFloat(ADR0CURRENT, 0.0);
  EEPROM.updateInt(ADR_WATCHDOGRESET, 0);

  writeIntConfigTable(recoveryProfile);
}
