[platformio]
default_envs = uno

[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 9600
lib_ldf_mode = deep+
build_flags =
    -I include

; Jesli potrzebujesz, odkomentuj i ustaw wlasny port:
; upload_port = COM5
; monitor_port = COM5

; Projekt zrodlowy wspomina o uzyciu bootloadera Arduino Uno dla poprawnej pracy watchdog.
